import 'package:garage/config/app_string.dart';

final Map<String, String> frFR = {
  AppString.alreadyHaveAnAccount: "Vous avez déjà un compte ?",
  AppString.appointments: "Rendez-vous",
  AppString.companies: "Compagnies",
  AppString.confirmPassword: "Confirmer votre mot de passe",
  AppString.home: "Accueil",
  AppString.emailHintText: "exemple@gmail.com",
  AppString.facebook: "Facebook",
  AppString.google: "Google",
  AppString.profile: "Mon Profil",
  AppString.nameHintText: "Votre nom",
  AppString.notMatch: "Pas de correspondance",
  AppString.orLogInWith: "Où",
  AppString.signIn: "Connectez-vous",
  AppString.signUp: "Créer un compte",
  AppString.seeAll: "Voir tous",
  AppString.serviceOperations: "Services",
  AppString.pleaseEnterConfirmPassword: "Confirmez votre mot de passe",
  AppString.pleaseEnterName: "Entrez votre nom",
  AppString.pleaseEnterBelowDetail: "Veuillez remplir le formulaire ci-dessous",
  AppString.pleaseEnterValidEmail: "Entrez une addresse valide",
  AppString.passwordHintText: "Mot de passe",
  AppString.pleaseEnterPassword: "Entrez votre mot de passe",
  AppString.notHavingAnAccount: "Vous n'avez pas de compte ?",
  AppString.welcome: "Bienvenu",
  AppString.error: "Erreur. Veuillez réessayer",
  AppString.retry: "Réessayer",
  AppString.logout: "Se déconnecter",
};
